import { environment } from "../../environments/environment.prod";

export const ENDPOINTS = {
    COMPANY: {
        ADD: "api/company/add",
        UPDATE: "api/company/update",
        DELETE: "api/company/deactive/guid",
        DETAIL: "api/company/detail/guid",
        GET_ALL: "api/company/list",
        GET_ALL_COMPANIES: "api/company/list/all",
        COUNT: "api/company/list/count",
        SITE_LIST: "api/company/site/list",
        LIST_ALL: "api/company/list/all",
    },
    PRODUCT: {
        ADD: "api/product/add",
        UPDATE: "api/product/update",
        DELETE: "api/product/deactive/guid",
        DETAIL: "api/product/detail/guid",
        GET_ALL: "api/product/list",
        COUNT: "api/product/list/count",
        FIND_BY_SKU: "api/product/locate/sku",
        FIND_BY_DESCRIPTION: "api/product/locate/description",
    },
    LOGON: "logon",
    USER: {
        ADD: "api/users/add",
        UPDATE: "api/users/update",
        DELETE: "api/users/deactive/guid",
        DETAIL: "api/users/detail/guid",
        GET_ALL: "api/users/list",
        COUNT: "api/users/list/count",
        GET_USERNAMES: "api/users/list/username",
        CHANGE_PASS: "api/users/updatepass",
        GET_ALL_BY_SITE: "api/users/list/site/guid",
    },
    SITE: {
        ADD: "api/site/add",
        UPDATE: "api/site/update",
        DELETE: "api/site/deactive/guid",
        DETAIL: "api/site/detail/guid",
        GET_ALL: "api/site/list",
        LIST: "api/site/list/all",
        COUNT: "api/site/list/count",
        FIND_BY_NAME: "api/site/locate/name",
        GET_ALL_NO_AUTH: "site-list",
    },
    PRINTER: {
        ADD: "api/printer/add",
        UPDATE: "api/printer/update",
        DELETE: "api/printer/deactive/guid",
        DETAIL: "api/printer/detail/guid",
        GET_ALL: "api/printer/list/siteGuid/",
        COUNT: "api/printer/list/count/siteGuid/",
        SITE_LIST: "api/printer/list/site/",
    },
    DASHBOARD: {
        UPDATE: "api/dashboard/update/site",
    },
    SPOOLER: {
        ADD: "api/spooler/add",
        UPDATE: "api/spooler/update",
        DELETE: "api/spooler/deactive/guid",
        DETAIL: "api/spooler/detail/guid",
        GET_ALL: "api/spooler/list",
        COUNT: "api/spooler/list/count",
        FIND_BY_USERNAME: "api/spooler/locate/username",
        CHANGE_PASS: "api/spooler/updatepass",
    },
    LABEL: {
        ADD: "api/label/add",
        UPDATE: "api/label/update",
        DELETE: "api/label/deactive/guid",
        DETAIL: "api/label/detail/guid",
        GET_ALL: "api/label/list",
        LIST: "api/label/list/all",
        COUNT: "api/label/list/count",
        FIND_BY_NAME: "api/label/locate/username",
        GET_PRINTER: "api/label/list-printer",
    },
    ORDER: {
        DELETE: "api/order/delete/number",
        DETAIL: "api/order/detail/guid",
        LIST: "api/order/list",
        COUNT: "api/order/list/count",
        ADD: "api/order/add/",
        UPDATE: "api/order/update/",
    },
    ORDER_DETAIL: {
        UPDATE_PRINTER: "api/order-detail/update-printer",
        UPDATE_LABEL: "api/order-detail/update-label",
        ADD: "api/order-detail/add",
        UPDATE: "api/order-detail/update",
        FIND_BY_NUMBER: "api/order-detail/locate/number",
        DELETE: "api/order-detail/delete/guid",
        DETAIL: "api/order-detail/detail/guid",
        OK: "api/order-detail/ok",
    },
    JOB: {
        TEST: "api/job/test",
        CREATE: "api/job/create",
        GET_PAGEABLE: "api/job/list/pageable",
        DETAIL: "api/job/detail/guid",
        SINGLE_PRINT: "api/job/single-print",
        JOB_QUERY: "job",
        JOB_COUNT: "api/job/list/pageable/count",
        SCAN_PRINT: "api/job/scan-print",
        CANCEL: "api/job/cancel/guid",
    },
    TAG: {
        TAG_QUERY: 'tag',
        TAG_SIMPLE: 'tag/simple',
        TAG_BATCH: 'api/tag/batch',
        TAG_BATCH_EAN: 'api/tag/batch',
        TAG_DEACTIVE_ALL: 'api/tag/deactive/all',
        TAG_DEACTIVE: 'api/tag/deactive/serial'
    },
    INVENTORY: {
        ADD: 'api/inventory/add',
        DETAIL: 'api/inventory/detail/guid',
        DELETE: 'api/inventory/delete/guid',
        GET_ALL: 'api/inventory/list',
        UPDATE: 'api/inventory/update',
        COUNT: 'api/inventory/list/count',
        GET_ITENS: 'api/inventory/detail/itens/guid'
    },
    ACCESS: {
        GET_ALL: "api/report/access/all",
        COUNT: "api/report/access/count",
    },
    PRINTS: {
        GET_ALL: "api/report/prints/all",
        COUNT: "api/report/prints/count",
    }
};

export const API_ENDPOINT = {
    URL_API: `${environment.apiUrl}/hb/`,
};
